LOAD DATA
characterset ZHS16GBK
INTO TABLE ibs_ptab_profitrate_tmp
TRUNCATE
FIELDS TERMINATED BY "|"
(  
PRODUCT_CODE  CHAR(10),
PRODUCT_NAME  CHAR(20),
BEGINDATE     CHAR(20),
BEGIN_AMOUNT  CHAR(20),
END_AMOUNT    CHAR(20),
RATE          CHAR(19),
PRODUCT_LIMIT CHAR(10),
ISROLL        CHAR(1),
RATEBASE      CHAR(10)
)