LOAD DATA
characterset ZHS16GBK
INTO TABLE IBS_TAB_AC_CHANGE
TRUNCATE
FIELDS TERMINATED BY "|+|"
(
LAOKAH     CHAR(16),
XINKAH     CHAR(16),
ZHANGH     CHAR(21),
JIOYRQ     CHAR(8),
YNGYJG     CHAR(4),
GUIYDH     CHAR(6),
BEIZXX     CHAR(128),
SHJNCH     INTEGER EXTERNAL,
RIZHXH     CHAR(25),
JILUZT     CHAR(1)
)
