LOAD DATA
characterset ZHS16GBK
INTO TABLE IBS_PTAB_BANKNO_TMP
TRUNCATE
FIELDS TERMINATED BY "|"
(
FQCYJG	CHAR(14),
JIGULB	CHAR(2),
HANBDM	CHAR(3),
FQZJJG	CHAR(14),
FRDBMC	CHAR(30),
BHSJCY	CHAR(130),
CJJGHH	CHAR(14),
GXRHHH	CHAR(14),
JIEDDM	CHAR(5),
RHDQDM	CHAR(6),
FUKRHM	CHAR(140),
CANSSJ	CHAR(10),
CANYBZ	CHAR(1),
CANJCC	CHAR(10),
DIHDIG	CHAR(30),
BENQQS	INTEGER EXTERNAL,
BEIYRQ	CHAR(8),
BYBZ01	CHAR(1),
XINX01	CHAR(60),
WEIHGY	CHAR(6),
WEIHRQ	CHAR(8),
SHJNCH	INTEGER EXTERNAL,
JILUZT	CHAR(1)
)