LOAD DATA
characterset ZHS16GBK
INTO TABLE IBS_TAB_FEE_ECCXBUSI_TMP
TRUNCATE
FIELDS TERMINATED BY "|+|"
(  
BILLNUM		CHAR(30),
TAG			CHAR(40),
TAGNAME1	CHAR(128),
TAGORDER1	CHAR(2),
SENDTAG1	CHAR(40),
TAGNAME2	CHAR(128),
TAGORDER2	CHAR(2),
SENDTAG2	CHAR(40),
SPECFLAG	CHAR(2),
REPEAFLAG	CHAR(1),
RESERVE1	CHAR(30),
RESERVE2	CHAR(30),
RESERVE3	CHAR(30),
RESERVE4	CHAR(30),
RESERVE5	CHAR(30)
 )
  
  
  