LOAD DATA
characterset ZHS16GBK
INTO TABLE IBS_ETAB_CIF_CUSTINFO_TMP
TRUNCATE
FIELDS TERMINATED BY "|+|"
(  
	CIF_NO				CHAR(15),	
	EC_CIF_NO			CHAR(10),	
	ORGAN_ID			CHAR(80),		
	CIF_NAME			CHAR(100),		
	CIF_OTHERFLAG	CHAR(2)		
)