LOAD DATA
characterset ZHS16GBK
INTO TABLE IBS_PTAB_XLBRANCH_TMP
TRUNCATE
FIELDS TERMINATED BY "|+|"
(  
BANK_CODE		CHAR(2),
ORGAN_ID		CHAR(4),
ORGAN_NAME	CHAR(62),
XL_AC				CHAR(20),
STATUS			CHAR(1)
)