LOAD DATA
characterset ZHS16GBK
INTO TABLE IBS_PTAB_GOLDTAKE_ORGAN_TMP
TRUNCATE
FIELDS TERMINATED BY "|"
(
PARAENT_ORGAN_ID       char(10),
PARAENT_ORGAN_NAME     char(200),
ORGAN_ID        char(10),
ORGAN_NAME      char(200),
ORGAN_ADDR      char(200),
ORGAN_POSTCDOE  char(6),
ORGAN_CON_NAME  char(32),
ORGAN_CON_TEL   char(20),
ORGAN_CON_PHONE char(20),
ORGAN_CON_EMAIL char(50)
)