LOAD DATA
characterset ZHS16GBK
INTO TABLE IBS_TAB_FEE_AERAINFO_TMP
TRUNCATE
FIELDS TERMINATED BY "|+|"
(  
CITYNO	CHAR(3),
CITYNAME	CHAR(20),
UCITYCODE	CHAR(3),
UCITYNAME	CHAR(20),
CITYLEVEL	CHAR(1),
CITYCODE	CHAR(4),
BRANCHID	CHAR(3),
SNDCITYCODE	CHAR(20),
RESERVE1	CHAR(20),
RESERVE2	CHAR(20)
)