LOAD DATA
characterset ZHS16GBK
INTO TABLE IBS_ETAB_FINANCEAMT_TMP
TRUNCATE
FIELDS TERMINATED BY "|+|"
(  
ORGAN			CHAR(4),
FUND_CODE		CHAR(24),
COMMIT_AMT		CHAR(16),
PAYE_AMT		CHAR(16),
SALES_AMT		CHAR(16),
NOW_MAYAMT		CHAR(16),
TIME			CHAR(16),
STATUS			CHAR(1),
JNL_NUMBER		CHAR(25)
)