LOAD DATA
characterset ZHS16GBK
INTO TABLE IBS_PTAB_CIF_LEVEL_TEMP
TRUNCATE
FIELDS TERMINATED BY "|+|"
(
CIF_NO     CHAR(10),
CIF_LEVELTYPE CHAR(30),
CIF_LEVEL  CHAR(20),
LEVEL_STARTDATE     DATE 'YYYYMMDD',
LEVEL_ENDDATE     DATE 'YYYYMMDD',
SYS_ID  CHAR(30),
CREATEDATE DATE 'YYYYMMDD'
)