LOAD DATA
characterset ZHS16GBK
INTO TABLE IBS_TAB_ESTOCK_ENTERPINFO_TMP
TRUNCATE
FIELDS TERMINATED BY "|+|"
(  
ENTERP_NO	CHAR(20),
ENTERP_NAME	CHAR(200),
STOCK_NO	CHAR(20),
STOCK_NAME	CHAR(200)
)