LOAD DATA
characterset ZHS16GBK
INTO TABLE IBS_ETAB_FUTURESCOMPANY_TMP
TRUNCATE
FIELDS TERMINATED BY "|+|"
(  
  FUTURESCOMPANY_ID    char(20),
  FUTURESCOMPANY_NAME  char(200),
  INPUTPASSWORDFLAG  char(1)
)