LOAD DATA
characterset ZHS16GBK
INTO TABLE IBS_TAB_FEE_BUSIAERA_TMP
TRUNCATE
FIELDS TERMINATED BY "|+|"
(  
	BILLNUM		CHAR(30),
	BILLBUSITYPE	CHAR(1),
	CITYLEVEL	CHAR(1),
	CITYID		CHAR(4),
	RESERVE1	CHAR(128),
	RESERVE2	CHAR(128)
)