LOAD DATA
characterset ZHS16GBK
INTO TABLE IBS_TAB_FEE_AUTH_TMP
TRUNCATE
FIELDS TERMINATED BY "|+|"
(  
	CHNLNO			CHAR(3),
	CHNLINSTNO	CHAR(15),
	BILLNUM			CHAR(30),
	FLAG				CHAR(1),
	PROFITCONF	CHAR(4),
	CLRCONF			CHAR(4)
)