LOAD DATA
characterset ZHS16GBK
INTO TABLE IBS_PTAB_PERLOANBRANCH_TMP
TRUNCATE
FIELDS TERMINATED BY "|+|"
(  
JNL_NO				CHAR(32),
PAR_TYPE			CHAR(2),
BANK_NAME			CHAR(32),
ADDRESS				CHAR(80),
PHONE					CHAR(32),
CONPHONE			CHAR(32),
BUSINESS_TYPE	CHAR(80),
ISLOOK				CHAR(2),
REMARK				CHAR(200),
INPUT_USERID	CHAR(32),
INPUT_ORGID		CHAR(32),
INPUT_DATE		Date 'YYYYMMDD',
UPDATE_USERID	CHAR(32),
UPDATE_ORGID	CHAR(32),
UPDATE_DATE		Date 'YYYYMMDD'
)