LOAD DATA
characterset ZHS16GBK
INTO TABLE IBS_MTAB_BASERATE
TRUNCATE
FIELDS TERMINATED BY "|"
(
  LILVBH CHAR(3),
  HUOBDH CHAR(2),
  LLBHLX CHAR(1),
  SHIJCQ CHAR(3),
  FEILDC CHAR(10),
  SXIORQ CHAR(8),
  LILVLL INTEGER EXTERNAL,
  NYUELL CHAR(1),
  SFBFDN INTEGER EXTERNAL,
  XFBFDN INTEGER EXTERNAL,
  SHFOBZ CHAR(1),
  SHMING CHAR(128),
  BYJC01 CHAR(6),
  SHJNCH INTEGER EXTERNAL,
  JILUZT CHAR(1)
)