insert into IBS_PTAB_FALLQUEUEJNL(JNL_NO,JNL_DATE,USER_ID,TRANS_CODE,AC_NO,AC_NAME,AC_ORGANID,AC_TYPE,CURRENCY,AC_NO2,AC_TYPE2,AC_NAME2,AC_BANK2,BANK_NO,AMOUNT,SUMMARY,TRSSTATUS,TRANS_TYPE,STATUS,TRANS_FREQUENCY,TIMES,REALFEE,MOBILE,FEE,INFORM,DE_AMOUNT,OUT_FLAG,ERRORMSG)
(
	select JNL_NO,JNL_DATE,USER_ID,TRANS_CODE,AC_NO,AC_NAME,AC_ORGANID,AC_TYPE,CURRENCY,AC_NO2,AC_TYPE2,AC_NAME2,AC_BANK2,BANK_NO,AMOUNT,SUMMARY,TRSSTATUS,TRANS_TYPE,STATUS,TRANS_FREQUENCY,TIMES,REALFEE,MOBILE,FEE,INFORM,DE_AMOUNT,OUT_FLAG,ERRORMSG
	from IBS_PTAB_FALLQUEUE
	where JNL_DATE < trunc(sysdate-1, 'dd')
);

delete from IBS_PTAB_FALLQUEUE
where JNL_DATE < trunc(sysdate-1, 'dd');
commit;
exit;