delete from IBS_PTAB_COUNYALIASCODEDZ t;
commit;
insert into IBS_PTAB_COUNYALIASCODEDZ
(GUOBDM,GUOJDM,GUOBJM,SUSHGJ,GUOJQC,DAZHOU,SUSDDM,SUSUDQ,SHJNCH,JILUZT) 
(select GUOBDM,GUOJDM,GUOBJM,SUSHGJ,GUOJQC,DAZHOU,SUSDDM,SUSUDQ,SHJNCH,JILUZT from IBS_PTAB_COUNYALIASCODEDZ_TMP a
);
commit;
exit;