delete from IBS_TAB_ESTOCK_ENTERPINFO t;
insert into IBS_TAB_ESTOCK_ENTERPINFO
  (ENTERP_NO, ENTERP_NAME, STOCK_NO, STOCK_NAME)
  (
  select ENTERP_NO, ENTERP_NAME, STOCK_NO, STOCK_NAME from IBS_TAB_ESTOCK_ENTERPINFO_TMP
  );
commit;
exit;