delete from ibs_tab_fee_billbusi t;
insert into ibs_tab_fee_billbusi
  (      fee_no,  trs_subcode, chrg_code, city_code,    city_name, item_no,     fee_com, busi_type,   item_name,    item_remark, qry_busicode, fee_busicode, filed_num, filed1, filed2, filed3, fee_rule,    charge_role, username_ctrl, busi_no, chk_times, card_flag, busi_flag,    up_citycode, list_num1, list_num2, list_num3, pay_type, per_type, per_amt, per_rate, hostno_flag, filed_uplim1, filed_lowlim1, filed_attr1, filed_type1, filed_uplim2, filed_lowlim2, filed_attr2, filed_type2, filed_uplim3, filed_lowlim3, filed_attr3, filed_type3, amt_uplim,    amt_lowlim,    amt_count,    amt1,    amt2,      amt3,     amt4,     amt5,     amt6,     amt7,     amt8,      amt9,     amt10,    start_time, end_time,   alias_flag, alias_name, rule_intruduct, filed_expl1, list_set1, filed_expl2, list_set2, filed_expl3, list_set3, bimg_path, limg_path, gttgfp_txt, chktimes_out, overdue_rule, PROVIDE_ELEMENTS,PRINT_LOCATION,LIMIT_CTRL,CLIENT_INPUT,
  FILED_SEND1,FILED_SEND2,FILED_SEND3,INTERFACE_DATASOURCES1,INTERFACE_DATASOURCES2,INTERFACE_DATASOURCES3,INTERFACE_DATASOURCES4,INTERFACE_DATASOURCES5)
  (
  select billnum, secondcode, chrgcode, billcitycode, billcity,  billtypenum, feecom, billbusitype, billtypename,    billinfo,    qrqbusicode,  billbusicode, filednum,  filed1,  filed2, filed3, chargerule, cchargerule, khxmkz,        busino,  chktimes,  cardflag,  busitypeflag, upcitycode,   listnum1, listnum2,   listnum3, paytype,  pertype, peramt,   perrate,   hostnoflag,  fileduplim1, filedlowlimi1,  filedattr1,  filedtype1,  fileduplim2,  filedlowlim2,  filedattr2,  filedtype2,  fileduplim3,   filedlowlim3, filedattr3,   filedtype3, billamtuplim, billamtlowlim, billamtcount, billamt1, billamt2, billamt3, billamt4, billamt5, billamt6, billamt7, billamt8, billamt9, billamt10, billtimed1, billtimed2, aliasflag,   aliasname, payruleintr,     filedexpl1, listset1,   filedexpl2, listset2,  filedexpl3,   listset3,  bimgpath, limgpath,  gttgfptxt, chktimesot,     znjrule,		ProvEle,				 PrintLoc,			ISLIMITCTRL,ISCLIENTINPUT ,
  RESERVE3,   RESERVE4,   RESERVE5,   Reserve11,             Reserve12,             Reserve13,             Reserve14,              Reserve15      from ibs_tab_fee_billbusi_tmp
  );
commit;
exit;