delete from IBS_ETAB_FUTURESCOMPANY;
insert into IBS_ETAB_FUTURESCOMPANY (FUTURESCOMPANY_ID,FUTURESCOMPANY_NAME,INPUTPASSWORDFLAG) 
                             (select FUTURESCOMPANY_ID,FUTURESCOMPANY_NAME,INPUTPASSWORDFLAG from IBS_ETAB_FUTURESCOMPANY_TMP);

commit;
exit;