update 
(
select b.AC_AUTHORTYPE b1,a.AC_AUTHORTYPE a1,b.AC_NO2 b2,a.AC_NO2 a2,
b.AC_NO b3,a.AC_NO a3,b.AC_NAME b4,a.AC_NAME a4,b.AC_TYPE b5,a.AC_TYPE a5,
b.AC_OPENBANKNO b6,a.AC_OPENBANKNO a6,b.AC_OPENBANKF b7,a.AC_OPENBANKF a7,b.AC_CURRENCY b8,a.AC_CURRENCY a8,
b.AC_BUSSINESSNO b9,a.AC_BUSSINESSNO a9,b.AC_EFFECTIVEDATE b10,a.AC_EFFECTIVEDATE a10,b.AC_EXPIRYDATE b11,a.AC_EXPIRYDATE a11,
b.AC_SINGLEAMOUNTLIMIT b12,a.AC_SINGLEAMOUNTLIMIT a12,b.AC_DATENUMLIMIT b13,a.AC_DATENUMLIMIT a13,b.AC_DATEAMOUNTLIMIT b14,a.AC_DATEAMOUNTLIMIT a14,
b.AC_MONTHNUMLIMIT b15,a.AC_MONTHNUMLIMIT a15,b.AC_MONTHAMOUNTLIMIT b16,a.AC_MONTHAMOUNTLIMIT a16 
from ibs_etab_super_ac a, ibs_etab_super_ac_temp b where a.CIFNO=b.CIFNO and a.PROTOCALNO=b.PROTOCALNO )
set a1=b1,a2=b2,a3=b3,a4=b4,a5=b5,a6=b6,a7=b7,a8=b8,a9=b9,a10=b10,a11=b11,a12=b12,a13=b13,a14=b14,a15=b15;
insert into ibs_etab_super_ac(
PROTOCALNO,CIFNO,AC_AUTHORTYPE,AC_NO2,AC_NO,AC_NAME,AC_TYPE,
AC_OPENBANKNO,AC_OPENBANKF,AC_CURRENCY,AC_BUSSINESSNO,AC_EFFECTIVEDATE,AC_EXPIRYDATE,
AC_SINGLEAMOUNTLIMIT,AC_DATENUMLIMIT,AC_DATEAMOUNTLIMIT,AC_MONTHNUMLIMIT,AC_MONTHAMOUNTLIMIT,
AC_NAME2,AC_OPENBANKNAME2,AC_OPENBANK2) 
(select PROTOCALNO,CIFNO,AC_AUTHORTYPE,AC_NO2,AC_NO,AC_NAME,AC_TYPE,
AC_OPENBANKNO,AC_OPENBANKF,AC_CURRENCY,AC_BUSSINESSNO,AC_EFFECTIVEDATE,AC_EXPIRYDATE,
AC_SINGLEAMOUNTLIMIT,AC_DATENUMLIMIT,AC_DATEAMOUNTLIMIT,AC_MONTHNUMLIMIT,AC_MONTHAMOUNTLIMIT,
AC_NAME2,AC_OPENBANKNAME2,AC_OPENBANK2 from ibs_etab_super_ac_temp a where 
not exists 
(
select b.CIFNO,b.PROTOCALNO from ibs_etab_super_ac b where a.CIFNO=b.CIFNO and a.PROTOCALNO=b.PROTOCALNO 
)
);
commit;
exit;