delete from IBS_PTAB_XLREMITCOUNYINFO t;
commit;
insert into IBS_PTAB_XLREMITCOUNYINFO
(COUNTRYCODE,CURRENCYCODE,COUNTRYNAME,BANKNO,CONTENT,SHJNCH,STATUS) 
(select COUNTRYCODE,CURRENCYCODE,COUNTRYNAME,BANKNO,CONTENT,SHJNCH,STATUS from IBS_PTAB_XLREMITCOUNYINFO_TMP a
);
commit;
exit;